testing new shell for windoes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -16,9 +16,24 @@ outputs:
 runs:
   using: "composite"
   steps:  
+      - name: Get shell name to use
+        id: shell_namer1
+        if: runner.os == 'Windows'
+        shell: wsl bash --noprofile --norc -euo pipefail "$(wslpath '{0}')"
+        run: |
+          echo "::set-output name=value::wsl bash --noprofile --norc -euo pipefail \"$(wslpath '{0}')\""
+
+      - name: Get shell name to use
+        id: shell_namer1
+        if: runner.os != 'Windows'
+        shell: bash
+        run: |
+          echo "::set-output name=value::bash"
+
       - name: Get bucket name
         id: bucket_namer
-        shell: bash
+        # Fun hack until we find a proper way: since only one of them will be executed, joining them gives us the correct result!
+        shell: ${{ steps.shell_namer1.outputs.value }}${{ steps.shell_namer2.outputs.value }}
         run: |
           b="${{ inputs.bucket }}"
           if [ -z "$b" ]; then
